from flask import Flask, render_template, request
import numpy as np
import joblib
from sklearn.preprocessing import LabelEncoder
import pandas as pd

app = Flask(__name__)

# Load the pre-trained model
model = joblib.load('trained_model.pkl')

df = pd.read_csv("final_grouped_dataset.csv")

label_encoder = LabelEncoder()
label_encoder.fit_transform(df['Restaurant Names'])
label_encoder.fit_transform(df['cuisines'])
label_encoder.fit_transform(df['Location'])

locations_hyderabad = [
 'L b nagar',
 'Koti',
 'Ramnagar',
 'S r nagar',
 'Shamshabad',
 'Abids',
 'Dilsukhnagar',
 'Basheer bagh',
 'Begum bazaar',
 'Somajiguda',
 'Ramanthapur',
 'Saroor nagar',
 'Adikmet',
 'Malakpet',
 'Meerpet',
 'Necklace road',
 'Kacheguda',
 'Lakdikapul',
 'Himayath nagar',
 'Mehdipatnam',
 'Kothapet',
 'Narayanguda',
 'Nadurgul',
 'Rajendra nagar',
 'Banjara hills',
 'Chandrayanagutta',
 'Panjagutta',
 'Langer houz',
 'Rtc x roads',
 'Khairatabad',
 'Musheerabad',
 'Amberpet',
 'Nallakunta',
 'Tolichowki',
 'Paradise',
 'Falaknuma',
 'Masab tank',
 'Charminar',
 'Secunderabad',
 'Nampally',
 'Ghansi bazaar',
 'Attapur']
n = ['Sri Raghavendra Udupi',
 'Sree Sai Satyanarayana Mithai Bhandar',
 'Al Ibrahim Hotel',
 'Sahadeva Reddy Chaat & Snacks',
 "Cake L'amore",
 'Taiba Bakery & Cafe',
 'Mini Box House Of Curries',
 "Mir's Grills N Garlics",
 'De Cafe Studio',
 'AS Kunafa',
 'Kings Mezbaan Restaurant',
 'Cakes Life',
 'Amma Chapathi Pulkha Roti Point',
 'Feng Shui Local Dabha',
 'Max Ice Cream & Bakers',
 'Victoria Cafe',
 'Gianis - Ice Cream, Shakes & Sundaes',
 'Rayalaseema Ruchulu',
 'Marvel Mandi',
 'Babai Grand Hotel',
 'Indari',
 'Chefs Best Plates',
 '1/2 Andhra Meals',
 'Dumont Creamery',
 'Straws The Cafe',
 'Kouzina Kafe - The Food Court',
 'Hotel Rumaan',
 "Express By AB's",
 'Grill Station',
 "Wendy's",
 'Mehfil Shawarma',
 'Sri Bhagyalaxmi Dhaba-2',
 'Sri Sai Veg Point',
 'Bajrang Chat Bhandar',
 'The Central Court Hotel',
 'Fabelle Chocolates',
 'Sri Narsing Bhelpuri & Juice Centre',
 'Nayaab Haleem An More',
 'VS Food Court',
 'Hasrat Catering India',
 'Roostys',
 'Victoria Restaurant',
 'Subbayya Gari Hotel',
 'Hotel Anand Bhavan Tiffins & Meals',
 'Hydrate The Bar - Hampshire Plaza',
 'Mandi Town',
 "Malik's Food Hub",
 'AL - Baik',
 'Mehfill-E-Sharwarma',
 'Noodles Express',
 'Rajthali',
 'Mamatha Darshini',
 "Nikhil's Hot & Spice Chinese Fast Food",
 'Bharpur Multicuisine Restaurant',
 'Shawarma Valley',
 'The Thickshake Project',
 'Barfi Delite',
 'Chacha Fast Food',
 'Chinese Hut Fast Food',
 'Shero Home Food - Andhra',
 'Angaara 5',
 'Waffle Hut',
 'Sri Ruchi Restaurant',
 'Al Arabia Shawarma',
 'The Pit Smokers',
 'Anni Rakala Amma Vantalu',
 'Mandi King Delite Arabian Restaurant',
 'Chubbs Chicken',
 'Cool Buzz',
 'Thali 99',
 'Hi King Bakers',
 'Imli Sarai',
 'Hilton Restaurant',
 'Panda Xpress',
 'Maggi House',
 'Cakes & Pastries',
 'Top Khana',
 'The Kulfi & Falooda Project',
 'Hotel Delhi Dastarkhan',
 'Homely Kitchen',
 'Al Azeem Cafe',
 'Balaji Mithai Bhandar',
 'Big Cheese Cafe',
 'Lassi & Falooda Co.',
 'Baker Street',
 'Mana Amma Curry Point And Mess',
 'Aruba Café',
 'Mashaallah Chaakna',
 'Kiranmai Food Court',
 'Peshawar Juice Centre',
 'Stop N Go Bakers',
 'Amma Garu Aya Garu Andhra Ruchulu',
 '1989 Milkshakes',
 'Francais Pizza',
 'Khush Di Rasoi',
 'Thanya Food House',
 'Amritsar Haveli',
 'Vaibhav Tiffins',
 'Cake Wala',
 'The Lassi Corner',
 'Express Fast Food',
 'The Ketchup Hall',
 'Sri Sai Raghavendra Udupi Veg',
 'The Board Game Cafe',
 'Royal Juice Centre',
 'Al Hashmi Arabian Shawarma & Fast Food',
 'Té - A Tea Tradition',
 'Cakes King',
 'Hotel Indu Deluxe',
 'Chopstix A Chinese Cuisine',
 'Veg Biryani House',
 'Hot Bucket Biryani',
 'Mithaiwala',
 'Momos & Fast Food',
 'Jaipur\'s Jalpoori - Chaats "n" More',
 'Hotel Sweekar',
 'Hotel Sitara Grand',
 'Raju Gari Homely Lunch Bojanam',
 'Kadir Nurman - Bonafide Shawarma',
 'Famous Momos And Fries',
 'Biryani Expres',
 'Natural Ice Cream',
 'Juice World',
 'Mandar',
 'Mandilicious',
 'US Pizza',
 'Butter Singh',
 'Gobblers Rolls & Bowls',
 'MH 999 Restaurant',
 'Telangana Amma Vantalu',
 'Haleem House',
 'Sweet Land Loops',
 'Gabru Di Chaap',
 'Astoria Restaurant',
 'Bench Cafe & Restaurant',
 'Shadaan Restaurant',
 'Badam And Kaju Ki Jali - The Imperial Sweet House',
 'Keshavam Family Restaurant',
 'Captain Kunafa',
 'Lucky Multicuisine Restaurant',
 'Signature Juice & Grill Station',
 'Sivaramareddy Ghee Sweets & Chat',
 'Journey 1853',
 'New Green Bawarchi',
 'Nimra Biryani Cafe',
 "Ohri's Ming's Court",
 'Aamantran Raga Sweets & Bakes',
 'Garden Street Kitchen',
 'Taste Corner',
 'B.Tech Chaiwala',
 'NTR Quick Bites',
 'Famous Ice Creams',
 "Grills 'N' Fries",
 'Sri Kanya',
 'Al Kareem Hotel',
 'Food.com',
 'Gullu Dadas Biryani',
 'Traffic Mandi House',
 'The Brooklyn Creamery - Healthy Ice Cream',
 'Jalpaan',
 'Dude Restaurant',
 'Rasna Buzz',
 'Kritunga',
 'The Tea Planet',
 "Alex's Kitchen",
 "Arabian Knight's Marhaba",
 'Veerji Ka Dhaba',
 'Shawarma Hot And Cool Point',
 'California Burrito',
 'Al Mattam Mandi',
 'Sri Balaji Ramsukh Family Dhaba',
 "Tibb's Frankie-Serving Rolls Since 1969",
 "Let's Scoop Ice Cream Cafe",
 'Snazzy Ice Cream',
 'Fruit Bowl Delight',
 'Panthashala',
 'Real Taste Chinese Fast Food',
 'Mehfil',
 'Dine Hill',
 'Mahalaxmi Tiffin Centre',
 'Aladdin Arabian Family Restaurant',
 'Balaji Chat Bhandar',
 "Peri's Kitchen",
 'A1 Golden Fast Food And Tea Point',
 'Punti Kura Pappu Dal Annam Very Tastly',
 'Turkish Shawarma House',
 'Chinna Inti Foods Curries',
 'Kabana',
 'Shahran Kebab',
 'Zaheer Juice Center',
 'Zaaika Foods',
 "Egg Morning - Omlette's",
 'Loukya Tasty Hub',
 'Dosha And Ponganalu Point Veg Nonveg',
 'Yaba',
 'Grameen Kulfi',
 'Roti Curry & Co',
 'Mubarak Arabian Mandi House',
 'La Milano Pizzeria',
 'Smaakenzzo',
 'Eggoholic',
 "Barrack's Grill",
 'Swaad Of South',
 'Cafe Coffee Day',
 'Burgasm',
 'Veg And Non Veg Curry Bazar',
 'Broast N Roast',
 'Firangi Fried Chicken',
 'House Of Wraps',
 'Taste Punjab Da',
 '99 Pancakes',
 'Sri Balaji Tasty Tiffins',
 'Cakes 99',
 'The Hot Bowl',
 'Swathi Hotel',
 'Hameedi Confectioner',
 'Mana Telangana Ruchulu',
 "Nikhil's Biryani House",
 'Italian Affair',
 'Saudagar Kalyani Biryani And Tahari',
 'Sahadeva Reddy Tiffins',
 "Graduate's Arabian Mandi",
 'Star Hotel',
 'Scoops Ice Cream',
 'Occasionkart Cakes',
 'Vantalakka Tiffins',
 'Tasty Crunch',
 'The Kunafa Kingdom',
 'Munch Chow Cafeteria',
 'Chinese Stories - Pan Asian',
 'Terra Cakes',
 'Doner King',
 'New Hotel Aalishan',
 'Wholesale Bakery',
 'Sri Lakshmi Fast Food',
 'K&C Bakers & Confectioners',
 'Minerva Coffee Shop',
 'Balaji Dinesh Mithai Bhandar',
 'Royal Biryani, Kabab & Juice Center',
 'MaMa B',
 'London Waffle Co.',
 'Parathawala',
 'Delights by INOX',
 'Alina Wraps',
 'Fantastic Four Cafe',
 'New York Waffles & Dinges',
 'Brioche The Bake House',
 'Alhamdulillah Chakna',
 'Ambika Tiffin Center',
 'New Hari Balaji Dhaba',
 'Tasty Fish Fry Point',
 'Surabhi Grand',
 'Biryani Mehfil',
 'Mana Inti Ruchulu',
 'Zaika Bites',
 '50 Fruits',
 'Green Dot Pizza',
 'Akbar Fast Food',
 'Chai Kings',
 'Varalakshmi Tiffins',
 'Ice Creamwalla & Co.',
 'Nanking Express',
 'Jain Kitchen Pure Vegetarian Restaurant',
 'The Wrap House',
 'MS Bakery & Sweets',
 'Momo Street',
 'Parampara - Flavours Of India',
 'Taj Mahal - Taj Mahal Hotel',
 "Bakers 'Q'",
 "4 Chili's Kitchen",
 'Yum Yum Noodle',
 'Cakes 07',
 'Sultan Darbar',
 'N Village',
 'Chinese Corner Restaurant',
 'Pista House Bakery',
 'Masqati True Juice',
 'Swagath Hotel',
 'Grand Bawarchi',
 "Dad's Kitchen",
 "Delish By Home's Kitchen",
 'Papacream',
 "Patel's Delights",
 'Subway',
 'Azizia Hotel',
 'Feel in Saudia',
 'JS Crispy Chicken',
 '11 Spices Multi Cusine Restaurant',
 'IGP Cakes',
 "Aroma's Of Golconda",
 'Healthy Food Restaurant',
 'The Kunafa Street',
 'RoosterX',
 'Starboy Pizza & Shakes',
 'Hotel Masha Allah Mandi',
 'Govind Dosa',
 'New Lavish Food Court',
 'Pista House Zafrani Tea',
 'Jalebiwala',
 'Bhavani Restaurant',
 'Lebanese Bites',
 'Rayala Seema Pattu',
 'Salasar Chat And Tiffins Center',
 'Cookie Man',
 'Hotel Shubham Palace',
 'Shahi Dastarkhwan',
 'Tashifa Home Make Foods',
 'Food Zone 2',
 'Bismillah Arabian Shawarma',
 'Fire & Ice Mandi Restaurent',
 'Saleem Ki Haleem By Hyderabad Spice',
 'Hotel Megha City',
 "Idhika's Cakes & Snacks",
 'Bowl 99',
 'Aahaa Food Court',
 'Amogham Restaurant',
 "Khatmandu Momo's",
 'Hive Honey Cake',
 'Hotel Sri Raghavendra Udupi Veg',
 'Amogh Multicuisine Restaurant',
 'The Royal Palace',
 'Village Style Dal 109 Verities Curries',
 'Laddu Ji',
 'Vinayak Tiffins',
 'Shawarma Buzz',
 'Anupama Hotel Veg & Non Veg',
 'A N S Family Special Foods',
 'TIB - The Icecream Bakery',
 'Street Falafel',
 "Vamshi's Noodles House",
 'Barista Coffee',
 'Andhra Inti Curries',
 'Shero Home Food - Chettinad',
 'Angeethi Asli Dhaba',
 'Bikaner Mithaiwala',
 'Starbucks Coffee',
 'Eat Full',
 'Chatori Chachi',
 'Al- Naseer Tahari Centre',
 'Rani Gari Chicken Fry Raju Gari Bagara Rice Center',
 'Wings To Heaven',
 'Abhi Ruchilu',
 'Lakshmi Restaurant',
 'Hotel Palace',
 'New Sai Kailash Dhaba',
 'Red Bucket Biryani',
 'Blend Healthy Combination',
 'Bawarchi Biryani & Haleem',
 'FullFills',
 'Hotel Ashoka Grand Udupi Veg',
 'Turkish Medbhee Restaurant',
 'Kebabzadeh',
 "King's Palace",
 'Mashallah Shawarma',
 'Under 79',
 'Pop Toad Bakers & Confectioners',
 'Arabian Food Court',
 'Peshawar',
 'The Mandi Kitchen',
 'New Delhi Mithaiwala',
 'Coffee And More',
 'Zain Sweets',
 'Andhra Bagara Rice Chicken Curry And Andhra Veg Meal',
 'Mumbaichee Chaat Street',
 'RHM Bakers',
 "Shezan Hotel & Baker's",
 'Turkish Doner',
 'FCH - Fried Chicken Hub',
 '10 RS Curry Point',
 'Pista House Mandi',
 'Al-Hamoor Cafeteria',
 'Shawarma House',
 'Lassi And Cream',
 'Santosh Family Dhaba',
 'Madhur Sweets',
 'Sha Sha Shandaar Shawarma',
 'Cravings Cafe',
 "Mughal's Bawarchi",
 'Pizzeria By Classico Italiano',
 'Green Kitchen',
 'UBQ by Barbeque Nation',
 'Temptations',
 'The Chocolate Room',
 'Sri Raadhe Chills & Thrills',
 'Sharmaji Pav Bhaji Centre',
 'Hotel N7 Elite',
 'Oven Spring Cake',
 'Maharaja Veg Biryani',
 'Blah Blah Resto Bake',
 'Minerva Sweets',
 'V Cafe- Meals By PVR',
 'Shawarma Bazaar',
 'A1 Fast Food And Nahari Centre',
 'Cassia - Hampshire Plaza',
 'Balaji Mukesh Mithai Bhandar',
 'Makkah Tiffin Centre',
 'NOTO - Healthy Ice Cream',
 "Ohri's Serengeti",
 '4 Seasons',
 'New Golden Baker',
 'Kafe Chai Nashta',
 'Polar Bear – Ice Cream Sundae Zone',
 'Andhra Ruchulu Akka Bavagaru',
 'Zaffran Mataam Alarabi',
 'Siddique Kabab Centre',
 'Exotica',
 'Papadams Blue',
 'Klip2deal Homefood',
 'Onesta',
 'Myfroyoland Premium Frozen Yoghurt',
 'The Olive Kitchen',
 'Norfest - The Dhaba',
 'Al Tazaj',
 'Ambika Foods',
 "Bowl O' China",
 'Al - Kusum Mandi',
 'Gusto Pizza',
 'Shawarma Time',
 'Tara Sweets & Chat',
 "Wendy's Burgers",
 '4M Biryani House',
 'Zam Zam Arabian Mandi',
 'Auberry The Bake Shop',
 'Bistro Bites',
 'Ruby Restaurant',
 'Venue - Quality Inn Residency',
 "Heaven's Grill",
 'Burger It Up',
 'New Santosh Dhaba',
 'New Al Qaswa Restaurant',
 'King Khaja Beef Mandi House',
 'Grand Bawarchi Restaurant',
 'Santosh Premium Dhaba',
 'Natural Juice Centre',
 'The Waffle Co',
 'Homely Quality Meal And Currys',
 'Cafe 111',
 'Ramnagar Bawarchi',
 'Rolls & Bowls By Feedx',
 'Pista Bakery',
 'Mataam AL Jazirah',
 'SJD Tea Cafe',
 'Nausheen Fruit Juice Centre',
 'Newly Telugu Curry Point',
 'Kebab Klub',
 'Kohinoor Food House',
 'Shahi Zaiqa',
 'Pitz Burg',
 'Central Bawarchi',
 'Tea Time',
 'Alhamdulillah Hotel',
 'Cups & Puffs',
 'Tea Club And Coconut Bar',
 'Biryani By Kilo',
 'Ofen',
 'The Oven',
 'Your Family Foods',
 'The Lassi Day',
 'Grand Hotel',
 "A'la Liberty",
 'Karachi Bakery',
 'Grill Tandoori Shawarma',
 'Gokul Dosa Ghar',
 'Rasa By Ashoka',
 'A Balaji Santosh Dhaba',
 'Grand Restaurant',
 'Indulge Ice Cream By Almond House',
 'Rice & Spices',
 'Krupa Mess & Tiffins',
 'Ritesh Family Dhaba',
 'Hotel Woodside',
 'Viva Italia',
 'Grill Xpress Restro',
 'Shero Home Food - North Indian',
 'Roll Zone',
 'King Ghouse Restaurant',
 "Ciro's Pizzeria",
 'Pista Kashmiri Tea Restaurant',
 'Crispy Crust',
 'House Of Milkshakes',
 'Padmavathi Tiffins',
 'Foodss Den',
 'Balaji Santosh Dhaba',
 'Kekiz Cake Shop',
 'Swathi Mess & Dhaba',
 'Kabul Darbar',
 'Alfa Sweets',
 'Southern Spice',
 'Layers - Cakes & Desserts',
 'Imran Restaurant',
 '100N',
 'Shawarma Delight',
 'Black Pearl - Hotel Central Park',
 'Mahendera Fast Food Center',
 "Haldiram's Sweets And Namkeen",
 'Harsh Chat Bhandar',
 'KS Bakers',
 'Rasoi Pure Veg Dhaba',
 'Mana Inti Bhojanam',
 'Waffle Studio',
 'Cakes Hub',
 'King Khaja Hotel',
 'Ram Ki Bandi',
 'Ankapur Chicken',
 'Red Dragon',
 'Kshetra',
 'Chizza Pizza',
 'Mandi King Elite Arabian Restaurant',
 'Burger Nine',
 'Puffs n Cakes',
 'Club 10 Chicken',
 "Zafar's Fine Dine",
 'Sweekar Chat',
 'Laffah Grills',
 "Dude! Where's My Burger",
 'Wahh Chaap & More',
 'Art Of Biryani',
 'Arabella',
 'Silver Salt',
 'Dum Safar Biryani',
 'Spice Express',
 'G. Pulla Reddy Sweets',
 'Instant Kitchen',
 'Fried Rice Turminal',
 'Jembo Pack Homely Meal',
 'Snappy Snacks Point',
 'Mataam Al Turky Family Restaurant',
 "Shawarma'z",
 'Grill Treat',
 'Ishaan Pizza Zone',
 'Idrees Food Shop',
 'Iqbal Cafe',
 'Palace Heights',
 'Ayagari Non Veg And Veg Home Foods',
 'Babuji Popcorn',
 'Oh My Shawarma',
 'Tree House Multi Cuisine Family Restaurant',
 'Yuva Fast Food Court',
 'Shahenshah Mandi',
 'Balapur Bawarchi Restaurant',
 'Desi Salads',
 'Swaad Veg',
 "Cake D'licious",
 'Bombay Bar & Restaurant',
 "Sahadeva Reddy's Juice Express",
 'Garam Bucket Biryani',
 'Splurge - Thickshakes And Milkshakes',
 'Balaji Santhosh Dhaba',
 'Pure Veg Meals By LunchBox',
 'Kamat Hotel',
 'Veggie Chinese',
 'Shalimar Sweets And Bakery',
 'Faasos Signature Wraps and Rolls',
 'Aazebo',
 'Hero Sandwich',
 'Nimrah Restaurant',
 'Riya Home Food Zone',
 'Classico Italiano',
 'A Bleu Basil - A Veg Affair',
 'Specially Really House Foods',
 'Noodle House',
 'Samtrupthi Foods',
 "Ohri's Gufaa",
 'Taj Mahal Hotel',
 'Meraj Naan',
 'City Spice Hotel',
 'Hotel City Diamond',
 'Maks Kitchen',
 "Lucky's Biryani House",
 "King's Chat Darbar",
 'Arabian Juices And Salads',
 'Lazeez Dastaan',
 'Sri Udupi Grand',
 'Biryani Hazir Ho',
 'Roti Point Box Pack',
 'The Night Crave',
 "AV's Smokebox",
 "The Absolute Biryani's",
 'Golden Zaiqa Restaurant',
 'AL Jamrah',
 'Papaji-Da-Dhaba',
 'Tara Juice World',
 'Sri Balaji Mithai Bhandar',
 'Fruitfull',
 'Al Saari Shawarma And Wraps',
 'NIC Ice Creams',
 'Amma Nanna Inti Foods',
 'Andhra Meals And Rolls  Zone',
 'Ammammagarillu',
 'Fast Food Home Made',
 '7 Sauces',
 'The Masala House',
 'Chat Corner',
 'Puliyogare Palace',
 'Cake Boyzs',
 'Capital Multi Cuisine Restaurant',
 'Tif In',
 'Spicy Noodle House',
 'FB Cakes',
 'The Hyderabad Chicken Haleem',
 'Andhra Rani Andhra Dhoragari Ruchulu',
 'Oven Story Pizza - Standout Toppings',
 'Headquarters',
 'MS Mandi & Shawarma',
 'New Shahi Naan',
 'Cream Stone Ice Cream',
 'Sri Gayathripuram Food Court',
 'Swap',
 'Shiv Shakti Jodhpur Sweets',
 'Khichdi Express',
 'Essa Shawarma',
 'Urban Munchies',
 'Voulga Hotel & Bakery',
 'Prem Di Rasoi',
 'LunchBox - Meals and Thalis',
 'Madam Gari Telangana Foods',
 'Teju Mess',
 'Chef O Menu',
 'Balaji Santosh Family Dhaba',
 'Sri Balaji Family Dhaba',
 'Gelato Burger House',
 'Chopstick Veg Restro',
 'Samdani Hotel',
 'Dostea',
 'Acme Candy Food',
 'The Good Bowl',
 'The Old School Caffe',
 'Italian Pizzeria',
 'Balaji Vishnu Sweet House',
 'Banjara 9 Restaurant',
 'Slurpy Shakes',
 'Mandi@37 Arabian Restaurant',
 'Bullet Bandi Curry Point',
 'Mataam Al Yamani',
 '65 Corner Fast Food',
 'Mini Punjab',
 'Kong Fu',
 'Fryed Wings',
 'Al Hashmi Shawarma Spot',
 'Star Rotis And Catering Service',
 'Ganga Rambhabu Currypoint And Mess',
 'Shahi Rasoi Multicuisine Family Restaurant',
 'Hotel Swagath',
 'Spice 6 - Global Dining',
 'Lassi Shop Hub',
 'Begum Bazar Dosa',
 'Elysium Creamery',
 'Amul Ice Cream Bigbite',
 'WOW! Momo',
 'Lassi N Cafe',
 'Grand Biryani',
 'Hotel Rajdhani',
 'China Town',
 'Naimat Delight',
 'New Agra Sweets',
 'Mohini Multicuisine Restaurant',
 'Balaji Mithai Wala & Chat',
 'Jumerah Arabian Mandi',
 'Aroma Family Restaurant',
 "McDonald's",
 'Big Bowl Chinese',
 "Harley's Fine Baking",
 'Jo Momo',
 'Ice And Spice',
 'Spicy Bucket Biryani',
 'Airport Bawarchi Restaurant',
 'N Village Restaurant',
 'Grill N Wrap',
 'Deccan Chef',
 'Apoorva Mess',
 'Small Home Meal And Currys',
 'Turkish Kitchen',
 'Wu -Tang',
 'La Mama',
 'Chinese House',
 'Santosh Fast Food',
 'Jai Durga Maa Apna Taste',
 'Hyderabad Mandi Town',
 'Sudha Ramya Homely Curry Point  Mess',
 'Feel In Saudi',
 'The Red Biryani',
 'Hotel Nakshatra Inn',
 'Nanamma Ruchulu',
 'Lassi & Shakes',
 'Al Madina Fast Food Centre',
 'Sri Balaji Prithviraj Family Dhaba',
 'Arun Ice Creams',
 'Mughlai Dastarkhwan Multi Cuisine Restaurant',
 'Mohammedia Mandi House',
 'Shahi Haleem',
 'Daawat Biryani Hub',
 'Eggiz - For Egg Lovers',
 'The Thickshake Factory',
 'Cost To Cost Curry Point',
 'Everything @145',
 'Pizza Delight',
 "Simpli Namdhari's Banjara Hills",
 'Ae Spice Villa',
 'Sarvi Restaurant',
 'Kiran Ki Rasoi',
 "Tibb's Frankie - Serving Rolls Since 1969",
 'Urban Beats Family Bar & Kitchen',
 'Blue Dragon By Mandilicious',
 'Hotel Shadab',
 'Arabian Central',
 'The Kunafa Station',
 'Meet N Pari Foods',
 'Pizza Hut',
 'Sweet Truth - Cake and Desserts',
 'New Alams',
 'Krispy Kreme',
 'Bismillah Khansa Tiffin  Centre',
 'Chandni Chowk',
 'Master Bucket Biryani',
 'MS Bakery',
 'Raju Gari Pulao',
 'Star Paan Shop',
 'Suprabath Tiffins',
 'The Dessert Zone',
 'My Crush Mandi Restaurant',
 'American Bakers',
 'Late Night Biryani',
 'Emerald Mithai Shop',
 'Hotel SVM Grand',
 'Chittemma Homely Bagara Rice Curries',
 'Emmy Biryani',
 'Bowls & Spoons',
 'Guru Amrit',
 'Exotic Momos',
 'Millet Express',
 'Mithai Mandir',
 'Firangi Bake',
 "Ohri's Eatmor",
 'Deccan Bakers and Sweet House',
 'Sri Ruchulu',
 "Dadu's",
 'MRCB',
 'Louis Burger',
 'Yo Chinese !',
 'New Ali Cafe',
 'Platform 65',
 'Beijing Bites',
 'Bakers Kitchen',
 'Telugu Vari Inti Ruchulu',
 'Begum Ki Biryani',
 'Sri Santosh Family Dhaba',
 'Masala Medley',
 'Aamantran Pure Veg',
 'FresHygiene@365',
 'Burger King',
 'Sunday Home Foods',
 'Dosa Street',
 'Mingle Maggi',
 'Sumaakshi Fast Food Adda',
 'Meethe Miya',
 "Jagavi's Restaurant",
 'Arabian Shawarma & Burger',
 'Dwaraka Veg Restaurant',
 'Indian Bakery',
 'Labonel Fine Baking',
 'The Snack Hack',
 'Narayan Upahaar',
 'Baskin Robbins - Ice Cream Desserts',
 'Chinese Kitchen',
 'Burger Hub',
 'Kulfi Nation',
 'Clouds Restaurant',
 'Balaji Food Court',
 'Naivedyam Family Dhaba',
 'Shree Lalla Dhaba',
 'Bagara Rice Meals Center',
 'Chai Point',
 'Arabic Kunafa',
 "1989 Pizza & Thick Shake's",
 'New Delhi Mithai Wala',
 'The Pizza Studio',
 'Froops',
 'Turkish',
 'Sri Santhosh Family Dhaba',
 "Anu's Food Court",
 'Delicious Dosa',
 "Ohri's Uppu",
 'RK Tiffins',
 'Masqati Ice Cream',
 'Chaat Cart',
 'Paradise Fast Food & Juice',
 'Pandu Fast Food Centre',
 '5 Rupee Andhra Curries',
 'Al Aqwan Bait Al Mandi',
 'Frosty Den',
 'S N Home Kitchen',
 'Italian Pizza Hub',
 'Sri Sapthagiri Restaurant & Bar',
 'Shah Ghouse Special Shawarma',
 'Al Saud Bait Al Mandi',
 'Bake Zone',
 'Spicy Hot Homely Meal',
 'Al Rahma Bakers And Sweets',
 'Al Ammar Arabian Cafeteria',
 'Lakhdatar Fast Food And Chat',
 '24/7 Biryani',
 "Gulbarga's Mama Puri And Special Snacks",
 'Cakes Online',
 'Sri Vaibhav Tiffins',
 'New Balaji Santosh Family Dhaba',
 'Maa Santosh Dhaba Family Restaurant',
 'Grills Corner',
 'Royal Tiffin Centre',
 'Broast Express',
 'Food Bucks',
 'N Spicy Bite Fast Food',
 'RRR',
 'Cuppa The Kitchen',
 'Holiday Eats',
 'Cheesecakes by CakeZone',
 'The Pork Affair',
 'Ice & Spice Restaurants',
 'Yummy Yummy Pizza',
 'Shah Shawarma',
 'Sri Jyothi Raghavendra Udupi Veg',
 'Telangana Curry',
 'Rayalavari Gayatri Ruchulu',
 'Pulao King',
 'TCS The Cake Story',
 'Mai Ki Rasoi',
 'The Exotic Shawarma',
 'Lucky Restaurant',
 'Ek Pyali Chai',
 'Feel In Saudia Shawarma',
 'Turkish Central',
 'Nasheman Hotel',
 'The Biryani Life',
 'Daruwaala',
 "DB's - Dum Pukht Biryani's",
 'Iceberg Organic Icecreams',
 'Body Power Cafe',
 'Sanjos Donuts',
 'Siri Tiffins',
 'Jai Bhavani Chat Bhandar',
 'Viceroy Restaurant & Bar',
 'Hi 5 Snack World',
 'Kwality Wall’s Frozen Dessert And Ice Cream Shop',
 'Gourmet Gully',
 'Hotel Sindhura East Court',
 'Eclair De Cake',
 'Arabian Shawarma',
 'Savera Hotel',
 'Angaara Kababs On Charcoal',
 "RK's Kitchen",
 'Vantinty Bagara Rice Center',
 '22 Homely Currys And Bagara Meal Center',
 'Veg Daawat By Behrouz',
 'Kung Pao Kitchen',
 'Tabla',
 'The Dessert Heaven - Pure Veg',
 'The Foodie Diet',
 'Annapurna Mess',
 'Muddapappu Avakai.com',
 "Momo Crave By AV's Smokebox",
 'Sri Darshini Pure Veg',
 'Chat Zone',
 'Muddapappu Avakaya & More',
 "Chotu's The Food People",
 'Kadupuninda Bojanam',
 "La Pino'z Pizza",
 'Snehitha Restaurant',
 'Sai Charan Dhaba 2',
 'Royal Juice Center',
 'Yashodamma Tiffins',
 '7 Hills Curry Point',
 'Pakka Local',
 'Hotel Miskeen',
 'Govind Gopal Hotel',
 'Sagar Papaji Ka Dhaba',
 'YMGA Food Studio',
 'Sai Raghavendra Bakers',
 'Bhagmati Biryani',
 'Rayees Shawarma',
 'Zaitun',
 'Dheeraj Fast Food',
 'Crave Adda',
 'ibaco',
 'Swagth Hotel',
 'Quality Shawarma',
 'Huber & Holly',
 'Zaiqa Arabian Food Court',
 'The Favorite Biryani And Shawarma',
 'Chilli & Spice',
 'Terrassen Cafe',
 'Delight Delicious',
 'Crystal Restaurant & Bar',
 'Gourmet Ice Cream Cakes by Baskin Robbins',
 'Yours Universe - Bakes & Cakes',
 'A2 Fast Food',
 'Bismillah Hotel',
 'Dev Rao Vilas',
 'Dark House',
 'Chicken Meal And Veg Meal 100 Family Verities',
 'Siddi Fast Food',
 'Abdullah Food Court',
 'Indiana Burgers',
 'MilletBowl by UrbanKisaan',
 'Bahar Biryani Cafe',
 'Radhe Family Dhaba',
 'Royal Meal And Curries',
 'Yousufain Drive In',
 'Al-Labbaik Shawarma',
 'Millet Bowl By UrbanKisaan',
 'Peppy Parathas & Rolls by Chai Point',
 'Ice Cafe & Lassi Shop',
 'Bhavani Pure Veg Tiffins & Snacks Centre',
 'Imperial Multi Cuisine Restaurant',
 'Kitchen Maha Raja',
 'Bakingo',
 'Urban Wok',
 'Mr. Doner House',
 'Italian Express',
 'Sattipandu Biryani',
 'Sri Sai Ram Darshini Tiffins & Meals',
 'Lucky Lucky',
 'Lebanese Doner',
 'Bagara Bowl',
 'Hotel Brundavan Pride',
 'Best Belgian Waffle',
 'Chaat Chaska',
 'Fusion Biryani',
 'Nonveg Homely Curry Point',
 'Naseeb Hotel',
 "Khaathwik's Kitchen",
 'Alhamdulilah Juice Centre',
 "Kiran's Food Court - KFC",
 'Hotel Mukarram',
 'Ragi Java Veg Non Veg',
 'Tewari Brothers Mithaiwala',
 'Chicken 65 Express',
 'Pranav Dhaba',
 'Ekathva Restaurant',
 'Haiking Chinese Restaurant',
 'Waffle House',
 'Tasty Momos',
 'Continue Night Way',
 'House Of Burger',
 'Al Akbar Fast Food Corner',
 'Al Rabea Al Arabi Cafeteria',
 'Blue Fox',
 'Office Box Meals ( Veg And Non Veg)',
 "Bhavi's Cafe",
 '7 Sisters',
 'Paradise Biryani',
 'Kwality Wall’s Frozen Dessert and Ice Cream Shop',
 'The Grill Corn3r',
 'Shahran Hotel',
 'Hotel Akbar Darbar',
 'Prasad Rolls & Parathas',
 'AL-Baik Arabian Cafeteria',
 'Euphoria Bakers',
 'Shahji Ka Dhaba',
 'Sohanlal Tea Point',
 'Kathmandu Momos',
 'Fancy Ice Cream',
 'Dubai Fried Chicken & Mutton',
 'Azaan Bait Al Mandi',
 'Oven Basket',
 'Agra  Sweet House',
 'Andhra Meals And Tiffins',
 'Gopal Vada Pav',
 'Varaahi Tiffins',
 'Shiva Chat Bhandar',
 'The Royal Paratha',
 'Scoops Tiffin Centre',
 'Under 99',
 '1 Kg Curries',
 'The Wrap Corner',
 'Spicy Hot Bucket Biryani',
 'Master Chef Indo Arabian Restaurant',
 'KFC',
 'Angaara',
 'Sams Kitchen',
 'Aroma Food Court',
 'Grand Bavarchi',
 'Pasha Naan',
 'Mandi House Arabian Restaurant',
 'Thinduda - A Telangana Kitchen',
 'Sri Siddartha Pure Veg',
 'Solana Food Court',
 'Gafoor Ice Cream',
 'D-Lite Frankie',
 'Sunny Bakers',
 'Healing Rice Bowls',
 'Hotel Swagath Grand',
 'A1 Chicken Pakoda Point',
 'Mayur Pan House',
 'Biryanis And More',
 'Charminar Tiffins',
 'Milan Bakery & Sweet House',
 'Sammis Shawarma',
 'Pasta Home',
 'Sri Balaji Jyothi Mithai Bhandar',
 "Papaji's Kitchen",
 'Biryani Box']

c = [
 'Afghan',
 'American',
 'Andhra',
 'Arabian',
 'Asian',
 'Assamese',
 'BBQ',
 'Bakery',
 'Bar Food',
 'Bengali',
 'Beverages',
 'Biryani',
 'Burger',
 'Burmese',
 'Cafe',
 'Chettinad',
 'Chinese',
 'Coffee',
 'Continental',
 'Desserts',
 'Fast Food',
 'Finger Food',
 'Frozen Yogurt',
 'Gujarati',
 'Healthy Food',
 'Hot dogs',
 'Hyderabadi',
 'Ice Cream',
 'Italian',
 'Japanese',
 'Juices',
 'Kebab',
 'Kerala',
 'Korean',
 'Lebanese',
 'Lucknowi',
 'Maharashtrian',
 'Mandi',
 'Mediterranean',
 'Mexican',
 'Mithai',
 'Momos',
 'Mughlai',
 'North Eastern',
 'North Indian',
 'Odia',
 'Oriental',
 'Paan',
 'Pakistani',
 'Pancake',
 'Panini',
 'Pasta',
 'Pizza',
 'Rajasthani',
 'Roast Chicken',
 'Rolls',
 'Salad',
 'Sandwich',
 'Seafood',
 'Shake',
 'Shawarma',
 'Sichuan',
 'Singaporean',
 'South Indian',
 'Street Food',
 'Sushi',
 'Tea',
 'Tex-Mex',
 'Thai',
 'Tibetan',
 'Turkish',
 'Waffle',
 'Wraps']


@app.route('/')
def home():
    return render_template('index.html' ,options = locations_hyderabad,names = n,cuisines = c)

@app.route('/predict', methods=['POST'])
def predict():
    # Get input values from user
    res = request.form['name']
    cui = request.form['cuisine']
    loc = request.form['location']
    rat = float(request.form['rating'])
    mino = float(request.form['minorder'])

    label_encoder_location = LabelEncoder()
    label_encoder_restaurant = LabelEncoder()
    label_encoder_cuisine = LabelEncoder()
    if res not in label_encoder.classes_:
        new_data = pd.DataFrame({
        'Restaurant Names': [res],
        'cuisines': [cui],
        'Location': [loc],
        'rating': [rat],
        'cost for one': [mino]
         })
        concatenated_data = pd.concat([df, new_data], ignore_index=True)
    
        concatenated_data['Location'] = label_encoder_location.fit_transform(concatenated_data['Location'])
        concatenated_data['Restaurant Names'] = label_encoder_restaurant.fit_transform(concatenated_data['Restaurant Names'])
        concatenated_data['cuisines'] = label_encoder_cuisine.fit_transform(concatenated_data['cuisines'])
    
        new_data_encoded = concatenated_data.iloc[-1:]
    
        predicted_time = model.predict(new_data_encoded[['Restaurant Names', 'Location', 'cuisines', 'rating', 'cost for one']])
    
        print("Predicted Time:", predicted_time[0])
    else:
        location_encoded = label_encoder.transform([loc])
        name_encoded = label_encoder.transform([res])
        cui_encoded = label_encoder.transform([cui])

        predicted_time = model.predict([[name_encoded,location_encoded, cui_encoded,rat,mino]])
        print("Predicted Time:", predicted_time[0])

    return render_template('index.html',options = locations_hyderabad,names = n,cuisines = c ,predicted_time="Predicted Time is "+str(round(predicted_time[0],2))+" min")
if __name__ == '__main__':
    app.run(debug=True)
